### ISSUE TITLE
Session lock when shutting down

### ISSUE THREAD

**Issue by cirosantilli** [xolox/vim-session#110]
On Ubuntu 14.04, gvim 7.4, if I shutdown the computer, and forget to explicitly close GVim before, a session lock remains, and I have to delete it when I restart.

Config:

      let g:session_autosave = 'yes'
      let g:session_autosave_to = 'default'
      let g:session_autoload = 'yes'

Not sure if this is a problem with this plugin or a general Vim problem. If someone can point me to the real source that would be awesome.

Possibly related to: https://github.com/xolox/vim-session/issues/97 , but ifi I close the window, the save works properly.

**Comment by xolox** [comment]
Hi Ciro and thanks for the feedback. This is related to #97 in the sense that:

1. Both issues concern the vim-session plug-in not properly releasing a lock file.

2. vim-session is not releasing the lock file because it isn't notified by Vim that it's being shut down (because Vim doesn't know either, until it's too late :-).

If there was a simple way to fix this I would have done it already, because it happens to me as well that I shut down my laptop without thinking about gracefully closing Vim and then next time I start Vim up I am greeted by the "locked session" message (which is definitely annoying when it happens too much).

----

For those who are following this issue and are interested in technical details:

1. The session lock files contain a process identifier or [PID](http://en.wikipedia.org/wiki/Process_identifier) for short, this is used to tell apart lock files "owned by" the currently running Vim instance from lock files owned by other Vim instances.

  *Sidebar: I explicitly went with PID tracking instead of Vim "server name" tracking because quite a few variations of Vim don't support that, e.g. console Vim in most circumstances!*

2. Vim's only interface to the existence of process identifiers is the [getpid()](http://vimdoc.sourceforge.net/htmldoc/eval.html#getpid()) function which returns the process identifier of the currently running Vim instance.

3. Vim doesn't have a function that enables the vim-session plug-in to tell whether a lock file is "stale" (owned by a Vim instance that no longer exists). One of the following functions could enable that behavior:

  1. A function to enumerate all of the process identifiers that are currently in use on a system.
  2. A function to check whether a given PID is still valid (something like `kill -0 ...` on UNIX systems).

Either of the functions above could be implemented in several ways (Python, interfacing with the shell, etc.) but all of those would be incomplete, very non portable and possible full of bugs depending on platform :-)

This actually points out a recurring problem and annoyance of mine in the world of Vim scripting: Catering to the lowest common denominator (either Windows or the fact that Vim script doesn't expose useful functionality) doesn't get you very far, so half of my Vim plug-ins are born handicapped :-(

----

I know that this long winded discussion doesn't actually solve a problem for you (yet) but it's useful to me:

1. To show that I put quite some thought into this already.

2. Taking next steps will involve me (my Vim plug-ins) stepping outside the world of Vim script functions and into the world of interfacing with either Python or external commands.

3. There are nevertheless options, I was just putting of having to step outside the world of Vim script because this always leads to increased complexity and platform specific behavior / bugs.

For something along the lines of a Python solution I was thinking of, the stackoverflow discussion [How to check if there exists a process with a given pid?](http://stackoverflow.com/questions/568271/how-to-check-if-there-exists-a-process-with-a-given-pid) shows possible solutions.

**Comment by xolox** [comment]
Hi Ciro!

A lesson I keep learning over the years is to be more pragmatic when possible: All of the complexity I previously mentioned is very interesting and all, but there's another more pragmatic way to deal with this issue which solves 90% of the problem in a very simple way.

In issue #101 another user suggested adding the option of storing lock files in the `/var/lock` directory on Linux. This directory is explicitly meant for lock files and doesn't persist between reboots, so by definition there will never be a stale lock file after a reboot! When I added that option I made it opt-in.

I've now decided to make this option opt-out. What this means is that if the user hasn't set the [session_lock_directory](http://peterodding.com/code/vim/session#session_lock_directory_option) option and the directory `/var/lock` exists and is writable, it will be used automatically.

I just published this change as vim-session 2.8 and I believe this resolves the issue you reported. Can you confirm?

**Comment by cirosantilli** [comment]
Thanks for awesome support xolox.

The fix does work on Linux, files under `/var/lock` get wiped away.

Let's hope / send feature requests to neovim so that we may be able to write better Vim plugins some day!
