### ISSUE TITLE
--servername doesn't work

### ISSUE THREAD

**Issue by dan-silva** [xolox/vim-session#115]
It looks like vim-session has some problem with [vim-startify](https://github.com/mhinz/vim-startify) when opening a session by using the `--servername` option. It doesn't open the existing session while vim-startify is enabled, instead it apparently just ignore the option.

**Comment by rosshadden** [comment]
`--servername` doesn't work for me either, and I don't have `vim-startify`.

**Comment by xolox** [comment]
@dan-silva: Thanks for the pull request in #116, that has now been merged and in my local testing it does indeed resolve the issue. If the problem has been resolved, can you close this issue? Thanks!

@rosshadden: That sounds like an unrelated problem (unrelated to the analysis by @dan-silva). If you want to get it fixed I suggest you [report a new issue](/xolox/vim-session/issues/new) that clearly describes the problem you're having. Note that because of this issue (#115) I extracted some start up logic into a separate function called [xolox#session#is_empty()](https://github.com/xolox/vim-session/#the-xoloxsessionis_empty-function) and that function is probably the one giving you problems.

**Comment by dan-silva** [comment]
Working perfectly! Thank you!
