### ISSUE TITLE
Update screenshots to show new dialog wording

### ISSUE THREAD

**Issue by roryokane** [xolox/vim-session#117]
The [README] contains two screenshots, “Screenshot of auto-save prompt” and “Screenshot of auto-open prompt”. [#104 “Make GUI dialogs from s:prompt easier to read”](https://github.com/xolox/vim-session/pull/104) made prompts look better, so the screenshots should be updated.

The images are hosted at http://peterodding.com/code/vim/session/, not in the repository, so GitHub contributors cannot edit the images.

Updating the screenshots will make visitors more likely to try vim-session out, because it will look slightly more usable.

---

As an example, this screenshot:

![README’s screenshot of auto-open prompt](http://peterodding.com/code/vim/session/autoopen.png)

should be retaken, so that its wording looks like this:

![recent screenshot of auto-open prompt in MacVim](https://cloud.githubusercontent.com/assets/79168/4622906/cb2ab8bc-5342-11e4-9c80-98fcf4010d10.png)

[README]: https://github.com/xolox/vim-session/blob/master/README.md

**Comment by xolox** [comment]
Hi Rory,

As mentioned in the commit message of 8670b1e I was already planning to update the screenshots, it just took me some time because I use a tiling window manager which hides all window decorations. Because I don't consider that very representative of the average environment I wanted to take screenshots that would include window decorations, so I needed to shut down my log-in session, switch to an alternative window manager, disable the vim-session option overrides in my `~/.vimrc` and finally take the screenshots I wanted :-).

FYI: I've moved the updated screenshots into the git repository, but please note that the readme contains absolute links instead of relative links at the moment (I know this isn't ideal). This is because the readme is rendered in more places than just on GitHub, specifically it is also rendered on my personal website and it's converted to a Vim help file that's bundled with the plugin. This explains why relative links won't work for my use cases.

Thanks for the feedback!
