### ISSUE TITLE
don't restore noexpandtab

### ISSUE THREAD

**Issue by atommixz** [xolox/vim-session#130]
I have this settings:

```vim
set noexpandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
```

but in restoring session i have every time expandtab.
Checked like `:set noet?`

Any suggestion?

**Comment by xolox** [comment]
Please try the following after loading a session:

```vim
:verbose set expandtab?
```

This should tell you from where the setting was last touched. By default vim-session doesn't persist Vim options so unless you significantly changed the defaults this shouldn't happen. Of course bugs are known to be a fact of life :-). That's why the output of the above command might help to understand what's going on. I'm half expecting this to print a message saying "Last set from modeline". That wouldn't give a full explanation yet but it would get us a lot closer.

**Comment by atommixz** [comment]
I do not know. I installed another linux distribution and it works. I'll open the question if the problem persists.
